### ISSUE TITLE
Code snippet has typos in DE version of the Gradle-Paper tutorial

### ISSUE THREAD

**Issue by Amejonah1200** [rainbowdashlabs/chojodev#3]
https://github.com/rainbowdashlabs/chojodev/blob/1ad42a693ce95d74e7f6c18b713b253762f34f38/docs/blog/de/gradle_minecraft_basic_and_advanced.md?plain=1#L241-L244

**Comment by rainbowdashlabs** [comment]
Why dont you make a PR? c:

**Comment by Amejonah1200** [comment]
Don't want to make a fork for just changing 2 chars...
